# Run linters automatically on pull requests.
name: Lint rosbag2
on:
  pull_request:

jobs:
  ament_copyright:
    name: ament_copyright
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: copyright
        distribution: rolling
        package-name: |
            ros2bag_future
            rosbag2_compression_future
            rosbag2_compression_zstd_future
            rosbag2_cpp_future
            rosbag2_test_common_future
            rosbag2_tests_future
            rosbag2_transport_future
            shared_queues_vendor_future

  ament_xmllint:
    name: ament_xmllint
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: xmllint
        distribution: rolling
        package-name: |
            ros2bag_future
            rosbag2_future
            rosbag2_compression_future
            rosbag2_compression_zstd_future
            rosbag2_cpp_future
            rosbag2_test_common_future
            rosbag2_tests_future
            rosbag2_transport_future
            shared_queues_vendor_future
            sqlite3_vendor_future
            zstd_vendor_future

  ament_lint_cpp: # Linters applicable to C++ packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify]
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: ${{ matrix.linter }}
        distribution: rolling
        package-name: |
            rosbag2_compression_future
            rosbag2_compression_zstd_future
            rosbag2_cpp_future
            rosbag2_test_common_future
            rosbag2_tests_future
            rosbag2_transport_future
            shared_queues_vendor_future

  ament_lint_python: # Linters applicable to Python packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [pep257, flake8]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: ${{ matrix.linter }}
        distribution: rolling
        package-name: |
            ros2bag_future
